# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u283NG9rz_jwzJhKJPUxf_GqqPLL26_h
"""

## Создание матрицы смежности

import json

with open('task.json', 'r') as file:
    tree = json.load(file)

def Check_depth(data, depth, parent=None):
  for key, value in data.items():
    if (int(key) > depth): depth = int(key)
    depth = Check_depth(value, depth, key)
  return depth

def create_matrix_of_zeroes(depth):
  matrix = []
  for i in list(range(depth)):
    matrix.append([0] * depth)
  return matrix

def write_adjacency(data, matrix, parent=None):
  for key, value in data.items():
    for i in value:
      matrix[int(key)-1][int(i)-1] = 1
      matrix[int(i)-1][int(key)-1] = 1
    matrix = write_adjacency(value, matrix, key)
  return matrix

write_adjacency(tree, create_matrix_of_zeroes(Check_depth(tree, 0, None)), None)